{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamspeak.mariadb.fullname" . }}
  labels:
{{ include "teamspeak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
{{ include "teamspeak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: primary
{{- end }}