{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "teamspeak.mariadb.fullname" . }}
  labels:
{{ include "teamspeak.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "teamspeak.mariadb.fullname" . }}
  replicas: {{ .Values.mariadb.primary.replicas | default 1 }}
  selector:
    matchLabels:
{{ include "teamspeak.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: primary
  template:
    metadata:
      labels:
{{ include "teamspeak.labels" . | nindent 8 }}
        app.kubernetes.io/component: primary
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mariadb
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag | default "11.5" }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "teamspeak.mariadb.fullname" . }}-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.auth.username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "teamspeak.mariadb.fullname" . }}-secret
                  key: mysql-password
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mariadb-config
              mountPath: /etc/mysql/conf.d
              readOnly: true
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-config
          configMap:
            name: {{ include "teamspeak.mariadb.fullname" . }}-config
            items:
              - key: my.cnf
                path: my.cnf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ {{ .Values.mariadb.primary.persistence.accessMode | quote }} ]
        {{- if .Values.mariadb.primary.persistence.storageClass }}
        {{- if (include "teamspeak.isStorageClass" (dict "storageClass" .Values.mariadb.primary.persistence.storageClass)) }}
        storageClassName: {{ .Values.mariadb.primary.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mariadb.primary.persistence.size }}
{{- end }}