apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "teamspeak.fullname" . }}
  labels:
{{ include "teamspeak.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "teamspeak.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "teamspeak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "teamspeak.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainer.enabled }}
      initContainers:
        - name: init-setup
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          {{- with .Values.initContainer.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
      {{- end }}
      containers:
        - name: ts-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TSSERVER_LICENSE_ACCEPTED
              value: {{ ternary "accept" "reject" .Values.licenseAccepted | quote }}
          ports:
            - name: voice
              containerPort: {{ .Values.voice.port }}
              protocol: UDP
            - name: filetransfer
              containerPort: {{ .Values.filetransfer.port }}
              protocol: TCP
            - name: webquery
              containerPort: {{ .Values.webquery.port }}
              protocol: TCP
{{/*TODO: Reactivate those probes! */}}
{{/*          {{- with .Values.livenessProbe }}*/}}
{{/*          livenessProbe:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
{{/*          {{- with .Values.readinessProbe }}*/}}
{{/*          readinessProbe:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "teamspeak.fullname" . }}-config
            defaultMode: 0644
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
        {{- if .Values.persistence.storageClass }}
        {{- if (include "teamspeak.isStorageClass" (dict "storageClass" .Values.persistence.storageClass)) }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}